name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install dependencies
        run: npm install 
      - name: start app
        run: node index.js
      - name: Deploy
        run: echo "deploying backend..."
